bundle:
  name: databricks-demo-bundle
  targets:
  dev:
    workspace:
      host: https://adb-7405618580636150.10.azuredatabricks.net/

  qa:
    workspace:
      host: https://adb-7405608612939104.4.azuredatabricks.net/
``
