name: Deploy Databricks Bundle to QA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_QA }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_QA }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@v0.211.0

      - name: Validate Bundle
        run: databricks bundle validate

      - name: Deploy to QA
        run: databricks bundle deploy --target qa
