name: Deploy Databricks Bundle to QA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@v0.211.0

      - name: Configure Databricks Auth
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_QA }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_QA }}" >> $GITHUB_ENV

      - name: Validate Bundle
        run: databricks bundle validate

      - name: Deploy to QA
        run: databricks bundle deploy --target qa
